apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: snapsure
data:
  MODEL_NAME: "xception"
  MODEL_DEVICE: "cpu"
  WEIGHTS_DIR: "/app/weights"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: snapsure
data:
  BACKEND_URL: "http://backend-service:8000"
