apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: snapsure
data:
  MODEL_DEVICE: "cpu"
  DEMO_MODE: "false"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: snapsure
data:
  BACKEND_URL: "http://backend-service:8000"
