apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: snapsure
data:
  MODEL_DEVICE: "cpu"
  DEMO_MODE: "false"
  XDG_CACHE_HOME: "/home/appuser/.cache"
  HF_HOME: "/home/appuser/.cache/huggingface"
  TORCH_HOME: "/home/appuser/.cache/torch"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: snapsure
data:
  BACKEND_URL: "http://backend-service:8000"
