apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: snapsure
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: snapsure
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
